spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    properties:
      schema: public
  pool:
    initial-size: 50
    max-size: 100
    enable: true
#
#    logging:
#      level:
#        org.springframework.r2dbc.core: debug
#        io.r2dbc.postgresql.QUERY: DEBUG # for queries
#        io.r2dbc.postgresql.PARAM: DEBUG # for parameters
#  debug: true